### ISSUE TITLE
The metadata hash field can only take 32 characters which is not correct

### ISSUE THREAD

**Issue by haizhouus** [algodesk-io/algodesk.io#9]
It should be able to take 32 BYTEs instead, which shall have different ways to input.

**Comment by algodesk-io** [comment]
Thanks for reporting. This is now fixed and deployed.

**Comment by prj-gh** [comment]
Hi, right now it looks as though the the binary representation of the text goes into the hash field. It would be great to parse the hash so that the binary hash itself went into the asset. Effectively, the length of the hash that can be used is being halved by storing the text representation of the hash.

E.g. if someone pastes a 32B SHA256 hash into the field in the asset creator the form will object since it is trying to put the ASCII representation of the hash into the asset (64B). 'a' becomes '01100001' instead of '1000'.

Using MD5 generates a text representation of the hash which is 32B so, fits, but it seems inefficient to store a character representation of the hash rather than the hash itself in the contract.

A work around would be to paste whatever text is generated by the binary hash, but in general this would include white space/function codes which are filtered out by the form.
